In [1]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
%matplotlib inline

from sklearn.naive_bayes import GaussianNB
from sklearn.decomposition import PCA
import datetime

In [2]:
ds = pd.read_csv('./train.csv')
data = ds.values[:, 1:]
labels = ds.values[:, 0]
print (data.shape, labels.shape)
print (data)

(42000, 784) (42000,)
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [3]:
data_size = data.shape[0];
split = int(0.8 * data_size)
X_train = data[:split, :]
y_train = labels[:split]

X_test = data[split:data_size, :]
y_test = labels[split:data_size]

print (X_train.shape, y_train.shape)
print (X_test.shape, y_test.shape)

(33600, 784) (33600,)
(8400, 784) (8400,)


In [4]:
gnb = GaussianNB()

gnb.fit(X_train, y_train)

gnb.score(X_test, y_test)

0.5619047619047619

In [7]:
pca = PCA(n_components=200)
X = pca.fit_transform(data)
print (X.shape)
v = pca.explained_variance_ratio_
cs = np.cumsum(v)
print (cs[-1])

data_size = X.shape[0];
split = int(0.8 * data_size)

X_train = X[:split, :]
X_test = X[split:data_size, :]

print (X_train.shape, y_train.shape)
print (X_test.shape, y_test.shape)

(42000, 200)
0.96625055733727
(33600, 200) (33600,)
(8400, 200) (8400,)


In [8]:
gnb = GaussianNB()

gnb.fit(X_train, y_train)

gnb.score(X_test, y_test)

0.8511904761904762