In [4]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
%matplotlib inline

from sklearn.decomposition import PCA
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score
import datetime

In [5]:
ds = pd.read_csv('./train.csv')
data = ds.values[:, 1:]
labels = ds.values[:, 0] 
print (data.shape, labels.shape)
print (data)

(42000, 784) (42000,)
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [8]:
pca = PCA(n_components=200)
X = pca.fit_transform(data)
print (X.shape)
v = pca.explained_variance_ratio_
cs = np.cumsum(v)
print (cs[-1])

(42000, 200)
0.9662068497153422


In [10]:
data_size = X.shape[0];
split = int(0.8 * data_size)
X_train = X[:split, :]
y_train = labels[:split]

X_test = X[split:data_size, :]
y_test = labels[split:data_size]

print (X_train.shape, y_train.shape)
print (X_test.shape, y_test.shape)

(33600, 200) (33600,)
(8400, 200) (8400,)


In [12]:
start = datetime.datetime.now()

knn = KNeighborsClassifier(n_neighbors=5, weights='distance')
knn.fit(X_train, y_train)
y_pred = knn.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)*100
end = datetime.datetime.now()

print ('Accuracy for K-Nearest Neighbours using sklearn: ', accuracy)
print ('Time Taken: ', (end - start).seconds, 'seconds')

Accuracy for K-Nearest Neighbours using sklearn:  97.28571428571429
Time Taken:  102 seconds
