In [1]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
import datetime
%matplotlib inline

from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

In [3]:
ds = pd.read_csv('./train.csv')

data = ds.values
print (data.shape) 
print (data)

(42000, 785)
[[1 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]
 ...
 [7 0 0 ... 0 0 0]
 [6 0 0 ... 0 0 0]
 [9 0 0 ... 0 0 0]]


In [7]:
split = int(0.8 * data.shape[0])
X_train = data[:split, 1:]
y_train = data[:split, 0]

X_test = data[split:split+2500, 1:]
y_test = data[split:split+2500, 0]

In [6]:
start = datetime.datetime.now()

knn = KNeighborsClassifier(n_neighbors=5, weights='distance')
knn.fit(X_train, y_train)
y_pred = knn.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)*100
end = datetime.datetime.now()

print ('Accuracy for K-Nearest Neighbours using sklearn: ', accuracy)
print ('Time Taken: ', (end - start).seconds, 'seconds')

Accuracy for K-Nearest Neighbours using sklearn:  97.48
Time Taken:  136 seconds
