In [1]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
from sklearn.decomposition import PCA
%matplotlib inline

In [3]:
ds = pd.read_csv('./train.csv')
data = ds.values[:, 1:]
labels = ds.values[:, 0]
print (data.shape, labels.shape)
print (data)

(42000, 784) (42000,)
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [18]:
split = int(0.8 * data.shape[0])
X_train = data[:split, 1:]
y_train = data[:split, 0]

X_test = data[split:split+2500, 1:]
y_test = data[split:split+2500, 0]
print (y_train)

[0 0 0 ... 0 0 0]


In [19]:
from sklearn.linear_model import LogisticRegression
LR = LogisticRegression()
LR.fit(X_train, y_train)

ValueError: This solver needs samples of at least 2 classes in the data, but the data contains only one class: 0

In [ ]:
print "Accuracy Training: ", LR.score(X_train, y_train)
print "Accuracy Testing: ", LR.score(X_test, y_test)